#——————————————————————————————————————————————————————————————————————————————
# The file has the content of the attributes dictionary of a received
# status-update object.
#  - Shows the Twitter API JSON data and their.
#  - Shows component objects — author/user, entities, extended_entities, and
#    place
#  - Inline annotations are mine.
#
# Rashad Barghouti
# Spring 2019
#——————————————————————————————————————————————————————————————————————————————
{
'quote_count': 0,
'contributors': None,
'truncated': True,
'text': u'The good news for now is that even when you\'re eulogized, yet are
still living -\n\nGod knows the difference, and \n\n"\u2026
https://t.co/OwoyJDOhEC',
'is_quote_status': False,
'in_reply_to_status_id': None,
'reply_count': 0,
'id': 1121341650528362508,
'favorite_count': 0,
'_api': <tweepy.api.API object at 0x7fe0ac28c250>,
'source': u'Twitter for Android',
# Begin Status JSON
'_json': {
    u'quote_count': 0,
    u'contributors': None,
    u'truncated': True,
    u'text': u'The good news for now is that even when you\'re eulogized, yet
    are still living -\n\nGod knows the difference, and \n\n"\u2026
    https://t.co/OwoyJDOhEC',
    u'is_quote_status': False,
    u'in_reply_to_status_id': None,
    u'reply_count': 0,
    u'id': 1121341650528362508,
    u'favorite_count': 0,
    u'entities': {
        u'user_mentions': [],
        u'symbols': [],
        u'hashtags': [],
        u'urls': [{
            u'url': u'https://t.co/OwoyJDOhEC',
            u'indices': [117, 140],
            u'expanded_url': u'https://twitter.com/i/web/status/1121341650528362508',
            u'display_url': u'twitter.com/i/web/status/1\u2026'
         }]
     },
     u'retweeted': False,
     u'coordinates': None,
     u'timestamp_ms': u'1556183657663',
     u'source': u'<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
     u'in_reply_to_screen_name': None,
     u'id_str': u'1121341650528362508',
     u'retweet_count': 0,
     u'in_reply_to_user_id': None,
     u'favorited': False,
     u'user': {
        u'follow_request_sent': None,
        u'profile_use_background_image': True,
        u'default_profile_image': False,
        u'id': 993917262590562305,
        u'default_profile': True,
        u'verified': False,
        u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'profile_sidebar_fill_color': u'DDEEF6',
        u'profile_text_color': u'333333',
        u'followers_count': 57,
        u'profile_sidebar_border_color': u'C0DEED',
        u'id_str': u'993917262590562305',
        u'profile_background_color': u'F5F8FA',
        u'listed_count': 5,
        u'profile_background_image_url_https': u'',
        u'utc_offset': None,
        u'statuses_count': 11177,
        u'description': u'Sourced from the Peculiar but still Pure Saint James River.',
        u'friends_count': 13,
        u'location': u'Manhattan, NY',
        u'profile_link_color': u'1DA1F2',
        u'profile_image_url': u'http://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'following': None,
        u'geo_enabled': True,
        u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/993917262590562305/1551803625',
        u'profile_background_image_url': u'',
        u'name': u'Rhys Tresi Myrrh',
        u'lang': u'en',
        u'profile_background_tile': False,
        u'favourites_count': 207,
        u'screen_name': u'PrairiesDawn',
        u'notifications': None,
        u'url': None,
        u'created_at': u'Tue May 08 18:15:16 +0000 2018',
        u'contributors_enabled': False,
        u'time_zone': None,
        u'protected': False,
        u'translator_type': u'none',
        u'is_translator': False
    },
    u'geo': None,
    u'in_reply_to_user_id_str': None,
    u'lang': u'en',
    u'extended_tweet': {
        u'display_text_range': [0, 279],
        u'entities': {
            u'user_mentions': [],
            u'symbols': [],
            u'hashtags': [{
                u'indices': [206, 212],
                u'text': u'olive'
            }],
            u'urls': []
        },
        u'full_text': u'The good news for now is that even when you\'re
        eulogized, yet are still living -\n\nGod knows the difference, and
        \n\n"Raises you up" as the way to "raise awareness to your
        plight"\n\nThe "beating of you" as the #olive branch he knew you to be
        in his intent when he sent you, Assigned.'
    },
    u'created_at': u'Thu Apr 25 09:14:17 +0000 2019',
    u'filter_level': u'low',
    u'in_reply_to_status_id_str': None,
    u'place': {
        u'full_name': u'Manhattan, NY',
        u'url': u'https://api.twitter.com/1.1/geo/id/01a9a39529b27f36.json',
        u'country': u'United States',
        u'place_type': u'city',
        u'bounding_box': {
            u'type': u'Polygon',
            u'coordinates': [[[-74.026675, 40.683935], [-74.026675, 40.877483],
                [-73.910408, 40.877483], [-73.910408, 40.683935]]]
        },
        u'country_code': u'US',
        u'attributes': {},
        u'id': u'01a9a39529b27f36',
        u'name': u'Manhattan'
    }
},
# End Status JSON
'coordinates': None,
'timestamp_ms': u'1556183657663',
'entities': {
    u'user_mentions': [], u'symbols': [],
    u'hashtags': [],
    u'urls': [{
        u'url': u'https://t.co/OwoyJDOhEC',
        u'indices': [117, 140],
        u'expanded_url': u'https://twitter.com/i/web/status/1121341650528362508',
        u'display_url': u'twitter.com/i/web/status/1\u2026'
    }]
},
'in_reply_to_screen_name': None,
'in_reply_to_user_id': None,
'retweet_count': 0,
'id_str': u'1121341650528362508',
'favorited': False,
'source_url': u'http://twitter.com/download/android',
'user': User(follow_request_sent=None, profile_use_background_image=True,
    _json={
        u'follow_request_sent': None,
        u'profile_use_background_image': True,
        u'default_profile_image': False,
        u'id': 993917262590562305,
        u'default_profile': True,
        u'verified': False,
        u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'profile_sidebar_fill_color': u'DDEEF6',
        u'profile_text_color': u'333333',
        u'followers_count': 57,
        u'profile_sidebar_border_color': u'C0DEED',
        u'id_str': u'993917262590562305',
        u'profile_background_color': u'F5F8FA',
        u'listed_count': 5,
        u'profile_background_image_url_https': u'',
        u'utc_offset': None,
        u'statuses_count': 11177,
        u'description': u'Sourced from the Peculiar but still Pure Saint James
        River.',
        u'friends_count': 13,
        u'location': u'Manhattan, NY',
        u'profile_link_color':
        u'1DA1F2',
        u'profile_image_url':
        u'http://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'following': None,
        u'geo_enabled': True,
        u'profile_banner_url':
        u'https://pbs.twimg.com/profile_banners/993917262590562305/1551803625',
        u'profile_background_image_url': u'',
        u'name': u'Rhys Tresi Myrrh',
        u'lang': u'en',
        u'profile_background_tile': False,
        u'favourites_count': 207,
        u'screen_name': u'PrairiesDawn',
        u'notifications': None,
        u'url': None,
        u'created_at': u'Tue May 08 18:15:16 +0000 2018',
        u'contributors_enabled': False,
        u'time_zone': None,
        u'protected': False,
        u'translator_type': u'none',
        u'is_translator': False
    }, # End User JSON
    id=993917262590562305,
    _api=<tweepy.api.API object at 0x7fe0ac28c250>,
    verified=False,
    translator_type=u'none',
    profile_image_url_https=u'https://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
    profile_sidebar_fill_color=u'DDEEF6',
    is_translator=False,
    geo_enabled=True,
    profile_text_color=u'333333',
    followers_count=57,
    protected=False,
    location=u'Manhattan, NY',
    default_profile_image=False,
    id_str=u'993917262590562305',
    utc_offset=None,
    statuses_count=11177,
    description=u'Sourced from the Peculiar but still Pure Saint James River.',
    friends_count=13,
    profile_link_color=u'1DA1F2',
    profile_image_url=u'http://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
    notifications=None,
    profile_background_image_url_https=u'',
    profile_background_color=u'F5F8FA',
    profile_banner_url=u'https://pbs.twimg.com/profile_banners/993917262590562305/1551803625',
    profile_background_image_url=u'',
    screen_name=u'PrairiesDawn',
    lang=u'en',
    profile_background_tile=False,
    favourites_count=207,
    name=u'Rhys Tresi Myrrh',
    url=None,
    created_at=datetime.datetime(2018, 5, 8, 18, 15, 16),
    contributors_enabled=False,
    time_zone=None,
    profile_sidebar_border_color=u'C0DEED',
    default_profile=True,
    following=False,
    listed_count=5),
'geo': None,
'in_reply_to_user_id_str': None,
'lang': u'en',
'extended_tweet': {
    u'display_text_range': [0, 279],
    u'entities': {
        u'user_mentions': [],
        u'symbols': [],
        u'hashtags': [{
            u'indices': [206, 212],
            u'text': u'olive'
        }],
        u'urls': []
    },
    u'full_text': u'The good news for now is that even when you\'re eulogized,
    yet are still living -\n\nGod knows the difference, and \n\n"Raises you up"
    as the way to "raise awareness to your plight"\n\nThe "beating of you" as
    the #olive branch he knew you to be in his intent when he sent you,
    Assigned.'
},
'created_at': datetime.datetime(2019, 4, 25, 9, 14, 17),
'author': User(
    follow_request_sent=None,
    profile_use_background_image=True,
    _json= {
        u'follow_request_sent': None,
        u'profile_use_background_image': True,
        u'default_profile_image': False,
        u'id': 993917262590562305,
        u'default_profile': True,
        u'verified': False,
        u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'profile_sidebar_fill_color': u'DDEEF6',
        u'profile_text_color': u'333333',
        u'followers_count': 57,
        u'profile_sidebar_border_color': u'C0DEED',
        u'id_str': u'993917262590562305',
        u'profile_background_color': u'F5F8FA',
        u'listed_count': 5,
        u'profile_background_image_url_https': u'',
        u'utc_offset': None,
        u'statuses_count': 11177,
        u'description': u'Sourced from the Peculiar but still Pure Saint James River.',
        u'friends_count': 13,
        u'location': u'Manhattan, NY',
        u'profile_link_color': u'1DA1F2',
        u'profile_image_url': u'http://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
        u'following': None,
        u'geo_enabled': True,
        u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/993917262590562305/1551803625',
        u'profile_background_image_url': u'',
        u'name': u'Rhys Tresi Myrrh',
        u'lang': u'en',
        u'profile_background_tile': False,
        u'favourites_count': 207,
        u'screen_name': u'PrairiesDawn',
        u'notifications': None,
        u'url': None,
        u'created_at': u'Tue May 08 18:15:16 +0000 2018',
        u'contributors_enabled': False,
        u'time_zone': None,
        u'protected': False,
        u'translator_type': u'none', u'is_translator': False
    },
    id=993917262590562305,
    _api=<tweepy.api.API object at 0x7fe0ac28c250>,
    verified=False,
    translator_type=u'none',
    profile_image_url_https=u'https://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
    profile_sidebar_fill_color=u'DDEEF6',
    is_translator=False,
    geo_enabled=True,
    profile_text_color=u'333333',
    followers_count=57,
    protected=False,
    location=u'Manhattan, NY',
    default_profile_image=False,
    id_str=u'993917262590562305',
    utc_offset=None,
    statuses_count=11177,
    description=u'Sourced from the Peculiar but still Pure Saint James River.',
    friends_count=13,
    profile_link_color=u'1DA1F2',
    profile_image_url=u'http://pbs.twimg.com/profile_images/1112960475296423936/KqDoRTMS_normal.jpg',
    notifications=None,
    profile_background_image_url_https=u'',
    profile_background_color=u'F5F8FA',
    profile_banner_url=u'https://pbs.twimg.com/profile_banners/993917262590562305/1551803625',
    profile_background_image_url=u'',
    screen_name=u'PrairiesDawn',
    lang=u'en',
    profile_background_tile=False,
    favourites_count=207,
    name=u'Rhys Tresi Myrrh',
    url=None,
    created_at=datetime.datetime(2018, 5, 8, 18, 15, 16),
    contributors_enabled=False,
    time_zone=None,
    profile_sidebar_border_color=u'C0DEED',
    default_profile=True,
    following=False, listed_count=5),
# End author object
'filter_level': u'low', 'in_reply_to_status_id_str': None,
# Begin Place object
'place': Place(_api=<tweepy.api.API object at 0x7fe0ac28c250>,
    country_code=u'US',
    url=u'https://api.twitter.com/1.1/geo/id/01a9a39529b27f36.json',
    country=u'United States',
    place_type=u'city',
    bounding_box=BoundingBox(_api=<tweepy.api.API object at 0x7fe0ac28c250>,
        type=u'Polygon',
        coordinates=[[[-74.026675, 40.683935], [-74.026675, 40.877483], [-73.910408, 40.877483], [-73.910408, 40.683935]]]),
    full_name=u'Manhattan, NY',
    attributes={},
    id=u'01a9a39529b27f36',
    name=u'Manhattan'),
# End Place object
'retweeted': False
}
# End Status object
