INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GOOGLEPUBSUB GooglePubSub)

FIND_PATH(
    GOOGLEPUBSUB_INCLUDE_DIRS
    NAMES GooglePubSub/api.h
    HINTS $ENV{GOOGLEPUBSUB_DIR}/include
        ${PC_GOOGLEPUBSUB_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GOOGLEPUBSUB_LIBRARIES
    NAMES gnuradio-GooglePubSub
    HINTS $ENV{GOOGLEPUBSUB_DIR}/lib
        ${PC_GOOGLEPUBSUB_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GOOGLEPUBSUB DEFAULT_MSG GOOGLEPUBSUB_LIBRARIES GOOGLEPUBSUB_INCLUDE_DIRS)
MARK_AS_ADVANCED(GOOGLEPUBSUB_LIBRARIES GOOGLEPUBSUB_INCLUDE_DIRS)

